### ISSUE TITLE
Bug in property constructor?

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#7]
in the Property constructor interface, there is no value parameter:
def __init__(self, propID, valueType, units, objectID=0):
Isn't this an error? Or has this class been deactivated on purpose for forcing the user to use ConstantProperty, which works fine?

**Comment by bpatzak** [comment]
The Property class is now (since last release 2.0) an abstract base class, its role is to declare common interface, however its instances should not be created, instead instances of derived classes should be created, implementing specific types of Property. You should use ConstantProperty, it should give the same behavior as the Property class in old MuPIF versions. We expect more derived classes in future, implementing, for example, time dependent properties, properties dependent on other variables, etc.
