### ISSUE TITLE
Error in distributed computing as in Example 11

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#8]
On my computer, I manage to run Example successfully. When I adapt this example for running with my API, the pyhton control script hangs, and one mupif server gives the following error:
************************
2018-03-07 17:22:50 INFO:JobMan2cmd.py:91 Running daemon on hosts 127.0.0.1 port 9200 nathost 127.0.0.1 natport 6200 hkey mupif-secret-key

2018-03-07 17:22:50 INFO:JobMan2cmd.py:91 Running daemon on hosts 127.0.0.1 port 9200 nathost 127.0.0.1 natport 6200 hkey mupif-secret-key

2018-03-07 17:22:50 INFO:JobMan2cmd.py:95 Initializing application with initial file input.in and workdir /home/rauchs/Modelling/testmupifdist4/WorkDir2/1@Mupif.JobManager@Solver2

2018-03-07 17:22:50 INFO:JobMan2cmd.py:95 Initializing application with initial file input.in and workdir /home/rauchs/Modelling/testmupifdist4/WorkDir2/1@Mupif.JobManager@Solver2

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mupif-2.0.0-py3.6.egg/mupif/tools/JobMan2cmd.py", line 124, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/mupif-2.0.0-py3.6.egg/mupif/tools/JobMan2cmd.py", line 96, in main
    app = conf.applicationClass(conf.applicationInitialFile, workDir)
  File "/home/rauchs/ComPoSTe/Interface/composteAPI.py", line 50, in __init__
    open(workdir+os.path.sep+file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/rauchs/Modelling/testmupifdist4/WorkDir2/1@Mupif.JobManager@Solver2/input.in'
************************
the error comes after the command in the python script:
app2 = PyroUtil.allocateApplicationWithJobManager( ns, JobMan2, cfg.jobNatPorts[0], cfg.hkey)

It looks like the dummy file name input.in, set in the serverConfig,py, does not point to the right input file. I noticed the following difference between the demoapp and my app:
- in the demo app, the input file is read later, in the solvestep method.
- in my app, the input file is read by the constructor __init__
Is it possible that this causes the error? And how to fix it? It does not seem reasonable to me to read the input file in the solvestep method, because this method is called once for every solution of a load increment. Unless it is restricted to the first execution of solvestep in an incremental analysis.

**Comment by grauchs** [comment]
The issue is resolved: I managed to read the input file in the constructor. It was an error of mine in the file name parameter!

**Comment by grauchs** [comment]
Sorry, it is not yet resolved. It is not possible to read the input file in the constructor! In fact, in the setting of Example11, the file input.in does not yet exist in the work directory during the execution of the constructor. It worked before because input.in existed in the work directory from a prervious run. The workaround I use for the moment is a logical flag, that is set to true when the model is read in, and methods of the API which are prone to be called first after the constructor and work on the model data check if the model has already been read in: if not it inputs the model and set the flag accordingly. But a better solution may be required!

**Comment by bpatzak** [comment]
The problem is complex, as in reality a complex setup procedure may be required (copying several files, license setup, etc.).
It is true, that the input file could not be opened from the constructor, as the file is available only later.
I see here two possibilities: 
- In constructor just remember the file name and open the file later (in solveYourself, for example), possibly introducing some flag to perform this action only once, as you have suggested.
- The input file could be located in common directory (prepared during server setup) on the server, and inptutFileName then could contain the full path to the common directory. Then api should not prepend workdir to file name when opening the input. This could be a reasonable solution, as in most cases the input will describe fixed part of the model shared with all executions)

More general solution would consist in extending the responsibilities of the application constructor, which should take care of setting up (copying) the working environment including input files, licenses, etc. In a such case, we need to pass additional arguments to the app constructor, but this can be done easily. 
Alternatively, the one could  edit JobMan2cmd.py script which actually setups and executes the application instance. By extending/modifying this script, any complex setup can be implemented. 

However, we prefer to perform the setup in constructor, as it is basically API which should implement (and hide) all application  specific details.
